// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopAPI.Models
{
    public partial class BankCard
    {
        public int CardId { get; set; }
        public int? UserId { get; set; }
        public string CardNumber { get; set; }
        public string CardholderName { get; set; }
        public string ExpiryDate { get; set; }
        public string Cvv { get; set; }
        public string BankName { get; set; }

        public virtual User User { get; set; }
    }
}