// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopAPI.Models
{
    public partial class ProductSize
    {
        public string ProductSizeId { get; set; }
        public string ProductId { get; set; }
        public string Size { get; set; }
        public int Stock { get; set; }

        public virtual Product Product { get; set; }
    }
}