// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopAPI.Models
{
    public partial class Product
    {
        public Product()
        {
            FavoriteProducts = new HashSet<FavoriteProduct>();
            OrderItems = new HashSet<OrderItem>();
            ProductSizes = new HashSet<ProductSize>();
        }

        public string ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public string ColorHex { get; set; }
        public string ColorName { get; set; }
        public int? CategoryId { get; set; }
        public string ImageUrl { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<FavoriteProduct> FavoriteProducts { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
    }
}