// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ShopAPI.Models
{
    public partial class User
    {
        public User()
        {
            BankCards = new HashSet<BankCard>();
            FavoriteProducts = new HashSet<FavoriteProduct>();
            Orders = new HashSet<Order>();
        }

        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string TypeAccount { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string HouseNumber { get; set; }
        public string BarcodeNumber { get; set; }

        
        public virtual ICollection<BankCard> BankCards { get; set; }
        public virtual ICollection<FavoriteProduct> FavoriteProducts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}